### ISSUE TITLE
コンパクトにできるんじゃ

### ISSUE THREAD

**Issue by c0a21109** [c0a21095/ProjExD#5]
https://github.com/c0a21095/ProjExD/blob/6e82a0576aed31625fc29dc85797f72aa3fe1ff2/ex02/calc.py#L44
for文のiを使って，"/"と"%"使った方がコンパクトになるんじゃ？？

**Comment by c0a21095** [comment]
ありがとうございます。ボタンのリストを1つにすることで、この部分を削減しました。想定していた対応とは異なると思いますが、ご了承ください。
