### ISSUE TITLE
カウントの位置

### ISSUE THREAD

**Issue by c0a21109** [c0a21095/ProjExD#6]
https://github.com/c0a21095/ProjExD/blob/e4ee320f27f80add4f33cd87faff0eda72346fa3/ex03/maze.py#L24
4１行目くらいでカウントを増やす作業をすれば，count+=1が1回でいいんじゃない？

**Comment by c0a21095** [comment]
コメントありがとうございます。
移動した瞬間に手数を増やすようにしているため、各if文内にcount += 1を配置しています。
このcount文を41行目に置いてしまうと、100ミリ秒ごとに自動で手数がカウントされてしまうため、実際の手数よりも遥かに多くの手数をカウントしてしまうこととなります。
ご理科頂けたら幸いです。
