### ISSUE TITLE
画像のロード

### ISSUE THREAD

**Issue by c0a21109** [c0a21095/ProjExD#8]
https://github.com/c0a21095/ProjExD/blob/55573e288ff6771c25850860f64b74dca4e98086/ex04/dodge_bomb.py#L58
while文の中でロードせずに，外で，名前を変えてロードしておいてから呼び出したほうがいいんじゃない？

**Comment by c0a21095** [comment]
ありがとうございます。各方向の画像をwhile文の外で定義するように変更しました。
