### ISSUE TITLE
関数化

### ISSUE THREAD

**Issue by C0A21069** [c0a21095/ProjExD#9]
https://github.com/c0a21095/ProjExD/blob/55573e288ff6771c25850860f64b74dca4e98086/ex04/dodge_bomb.py#L25
同じことを書いているから関数にしたほうがいいかもしれない

**Comment by c0a21095** [comment]
ありがとうございます。4限中に関数やクラスとしてまとめたかったのですが、残り時間が少なく実装できませんでした。
